### ISSUE TITLE
Books still cut off at the end of list, new margin appears over listings.

### ISSUE THREAD

**Issue by SleepyScribe** [aloussase/AlexandriaApp#29]
**Version:** 0.3.3
**Phone:** Pixel 7 Pro
**Android Version:** 14

**Steps to recreate:** Search for something with a long listing, such as "Bag of Bones". Scroll to the bottom of the list. Actual book is cut off at the top of the new margin. Can reproduce with other books that have long listings.

**Suggested workaround:** Instead of adding margins to the fixed navigation bar, which didn't seem to work in my case, adding a blank entry at the end of every list could prove an effective workaround. I'm not sure how Kotlin works, but if it takes anything similar to CSS/HTML, you could also add an invisible element with the same height specifications as the navbar at the bottom of the listing element.

Users not experiencing the bug would just see a bit of blank space at the bottom. I'd remove the margin from the navbar, as it appears over the listings as I scroll.

**Alternative advanced fix:** Could also have the menu disappear on scroll down and reappear when scrolling back up. I've seen apps do this, but I have 0 experience with Kotlin and Android development in general, so I wouldn't have the first idea of how to implement this other than finding another open source app that does it and then, well... monkey see, monkey do.

I love the app and I hope this helps. I enjoy using fixed navbars in my pages, but making them gives me a headache. I usually do the first suggested fix above and throw in a div with the same dimensions underneath them because I'm too dumb to do it properly.

**Comment by aloussase** [comment]
These are great suggestions, thank you very much! Right now I am a bit busy with school but i will see what a I can do as soon as possible!

**Comment by aloussase** [comment]
Hi there! Finally got some time for this. Turns out your proposed advanced solution was just one StackOverflow search away! https://stackoverflow.com/questions/44777869/hide-show-bottomnavigationview-on-scroll.

Sadly, I had to go with the uglier solution because I am maintaining some legacy devices, but hey, it works! It's not perfect (maybe just a bit sluggish on debug mode) but I think it works nicely.

Expect the update in the next release on F-Droid.

I'm gonna be closing this issue for now, but feel free to re-open it if the issue does not go away.
